name: Daily update

on:
  #schedule:
    # 2時間ごとに処理実行
  #  - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Updater
        uses: actions/checkout@v3
        with:
          repository: nandroid3/market-price-updater-js
          path: market-price-updater-js
          token: ${{ secrets.GH_PAT }}
   
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          path: market-price-updater-js-action
   
      - name: Package install
        run: npm install
        working-directory: market-price-updater-js

      - name: Run
        run: npm run daily
        working-directory: market-price-updater-js
        
      - name: Check
        run: |
          pwd
          echo "----"
          ls
          echo "----"
          ls market-price-updater-js
          echo "----"
          ls market-price-updater-js/data/ref
          echo "----"
        
      - name: Copy files
        run: |
          pwd
          echo "----"
          ls market-price-updater-js-action
          echo "----"
          cp ./market-price-updater-js/data/ref/sp500.csv ./market-price-updater-js-action/data/ref/sp500.csv
        
      - name: Commit
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "daily update"
          git push
        working-directory: market-price-updater-js-action
